/** Audit every local 5etools JSON file. Run: npm run audit:data [-- --write]. */
import { readdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = fileURLToPath(new URL("../", import.meta.url));
async function filesUnder(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  return (await Promise.all(entries.map((entry) => {
    const target = path.join(directory, entry.name);
    return entry.isDirectory() ? filesUnder(target) : [target];
  }))).flat().sort();
}

const dataFiles = (await filesUnder(path.join(root, "public/data")))
  .filter((file) => file.endsWith(".json"));
const serviceFiles = (await filesUnder(path.join(root, "src/services")))
  .filter((file) => file.endsWith(".ts") && !file.includes("_tests_"));
const consumers = await Promise.all(serviceFiles.map(async (file) => ({
  file: path.relative(root, file).replaceAll("\\", "/"),
  text: await readFile(file, "utf8"),
})));
const rows = [];
for (const file of dataFiles) {
  const relative = path.relative(root, file).replaceAll("\\", "/");
  const json = JSON.parse(await readFile(file, "utf8"));
  const collections = Object.entries(json).filter(([key, value]) =>
    !key.startsWith("_") && Array.isArray(value));
  const records = collections.flatMap(([, value]) => value);
  rows.push({
    file: relative.replace("public/", ""),
    collections: collections.map(([key, value]) => `${key}: ${value.length}`).join("; ") || "Lookup / curated lore",
    consumers: consumers.filter((service) => service.text.includes(`@/${relative}`)).map((service) => service.file),
    records: records.length,
    sources: [...new Set(records.map((record) => record?.source).filter(Boolean))].sort(),
    inherited: records.filter((record) => record?._copy).length,
  });
}

const unreferenced = rows.filter((row) => row.consumers.length === 0);
const report = [
  "# Local 5etools Data Audit",
  "",
  "Generated by `npm run audit:data -- --write`. Re-run after adding or pruning data.",
  "",
  `Inspected **${rows.length} JSON files** and **${rows.reduce((sum, row) => sum + row.records, 0)} top-level collection records**. **${unreferenced.length} files have no service import**. Lookup and lore objects are counted as files, not collection records.`,
  "",
  "## What this verifies",
  "",
  "Every JSON parses and has an explicit data-service consumer. An import proves file reachability, not that every record, field, or described mechanic is implemented. Catalog integration tests separately check normalized 2024 options, spell lists, and feature references.",
  "",
  "Classes, species, backgrounds, languages, and feats use the 2024 catalog policy (XPHB or edition `one`). Subclasses follow the selected class version. Spells and equipment retain supplemental catalogs; active-source preferences control availability. Legacy PHB choices remain inactive; other equipment sources remain selectable. Reprinted equipment is retained when its replacement is unavailable locally. No raw input is modified by this audit.",
  "",
  "## File inventory",
  "",
  "| File | Collections | Service consumers | Inherited records |",
  "| --- | --- | --- | ---: |",
  ...rows.map((row) => `| \`${row.file}\` | ${row.collections} | ${row.consumers.map((consumer) => `\`${consumer}\``).join(", ") || "**MISSING**"} | ${row.inherited} |`),
  "",
  "## Interpretation and remaining scope",
  "",
  "- `spells/sources.json` joins spell identities to class lists; it is not a spell catalog itself.",
  "- `player-lore.json` supplies curated descriptions and images; it does not override mechanics.",
  "- Class and subclass feature records are resolved through their full 5etools references, including an explicit feature source when supplied.",
  "- Nested item groups, item properties, optional-feature references, conditional effects, and free-text rules require dedicated adapters or table adjudication. Loading their containing file does not imply automation.",
  "- Multiclassing and comprehensive automation of all feats, species spells, subclass spells, and magic-item conditions remain outside the implemented rules coverage.",
  "",
].join("\n");
if (process.argv.includes("--write")) {
  await writeFile(path.join(root, "guides/5etools-data-audit.md"), report);
}
console.log(JSON.stringify({ files: rows.length, records: rows.reduce((sum, row) => sum + row.records, 0), unreferenced: unreferenced.map((row) => row.file), inventory: rows }, null, 2));
if (unreferenced.length > 0) process.exitCode = 1;
